### ISSUE TITLE
Is there a way to reduce the size of the docker container?

### ISSUE THREAD

**Issue by AdityaAnand1** [zenato/puppeteer-renderer#31]
![image](https://user-images.githubusercontent.com/13274079/99684459-7f628480-2aa7-11eb-8163-a548340806fb.png)

Uncompressed, it's a whopping 2.29 GB. Is there anything more we could do to trim this down?

Random idea: Maybe use a slimmer chrome alternative e.g. https://github.com/alixaxel/chrome-aws-lambda?

**Comment by zenato** [comment]
@AdityaAnand1 
puppeteer-renderer depends on [zenato/puppeteer](https://github.com/zenato/docker-puppeteer) docker image.
I tried changing the base image of zenato/puppeteer, but there wasn't much difference.
It's because docker image includes google chrome,  puppeteer and node libraries.

Currently I use Google Chrome as in the official docs and other environments like aws-lambda will be considered in the next major version update.

Thanks.

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker
